{-# LANGUAGE GADTs #-}
{-# LANGUAGE DataKinds #-}
{-# LANGUAGE TypeFamilies #-}
{-# LANGUAGE PatternSynonyms #-}
{-# LANGUAGE ViewPatterns #-}
{-# LANGUAGE LambdaCase #-}
{-# LANGUAGE OverloadedStrings #-}
{-# LANGUAGE FlexibleInstances #-}
{-# LANGUAGE TypeApplications #-}
{-# LANGUAGE UndecidableInstances #-}
{-# LANGUAGE RankNTypes #-}

-- | Example: Display DSL for STLC terms.
--
-- This demonstrates the pattern synonym approach where users write
-- display rules using familiar syntax.
module TypedRedex.Free.Display.Example where

import Data.String (IsString(..))
import Data.Typeable (Typeable, typeRep)
import Data.Proxy (Proxy(..))

--------------------------------------------------------------------------------
-- Display Expression (from Display.hs)
--------------------------------------------------------------------------------

data D
  = Lit String
  | Child Int
  | Seq D D
  | Parens D
  | Empty
  deriving (Show, Eq)

instance IsString D where
  fromString = Lit

instance Semigroup D where
  Empty <> y = y
  x <> Empty = x
  x <> y     = Seq x y

instance Monoid D where
  mempty = Empty

parens :: D -> D
parens = Parens

renderD :: (Int -> String) -> D -> String
renderD _     (Lit s)     = s
renderD child (Child i)   = child i
renderD child (Seq a b)   = renderD child a ++ renderD child b
renderD child (Parens d)  = "(" ++ renderD child d ++ ")"
renderD _     Empty       = ""

--------------------------------------------------------------------------------
-- Original User Types
--------------------------------------------------------------------------------

data Nat = Z | S Nat
  deriving (Eq, Show)

data Ty = TUnit | TArr Ty Ty
  deriving (Eq, Show)

data Tm
  = Var Nat
  | Unit
  | Lam Tm
  | App Tm Tm
  | Ann Tm Ty
  deriving (Eq, Show)

--------------------------------------------------------------------------------
-- Pattern Synonyms for Display DSL
--
-- These would be generated by TH in practice.
-- The key: children become 'D' placeholders (Child 0, Child 1, etc.)
--------------------------------------------------------------------------------

-- | Pattern type: constructor name + children as D
data Pat a = Pat String [D]
  deriving (Show)

-- Nat patterns
pattern Z_ :: Pat Nat
pattern Z_ = Pat "Z" []

pattern S_ :: D -> Pat Nat
pattern S_ n = Pat "S" [n]

-- Ty patterns
pattern TUnit_ :: Pat Ty
pattern TUnit_ = Pat "TUnit" []

pattern TArr_ :: D -> D -> Pat Ty
pattern TArr_ a b = Pat "TArr" [a, b]

-- Tm patterns
pattern Var_ :: D -> Pat Tm
pattern Var_ n = Pat "Var" [n]

pattern Unit_ :: Pat Tm
pattern Unit_ = Pat "Unit" []

pattern Lam_ :: D -> Pat Tm
pattern Lam_ b = Pat "Lam" [b]

pattern App_ :: D -> D -> Pat Tm
pattern App_ f x = Pat "App" [f, x]

pattern Ann_ :: D -> D -> Pat Tm
pattern Ann_ e t = Pat "Ann" [e, t]

--------------------------------------------------------------------------------
-- User-Written Display Rules (This is what users write!)
--------------------------------------------------------------------------------

-- | Display rules for Nat - looks like pattern matching on Nat!
natDisplay :: Pat Nat -> D
natDisplay = \case
  Z_   -> "0"
  S_ n -> "S " <> n

-- | Display rules for Ty
tyDisplay :: Pat Ty -> D
tyDisplay = \case
  TUnit_     -> "Unit"
  TArr_ a b  -> a <> " → " <> b

-- | Display rules for Tm - exactly the syntax the user wanted!
tmDisplay :: Pat Tm -> D
tmDisplay = \case
  Var_ n     -> "var " <> n
  Unit_      -> "()"
  Lam_ b     -> "λ. " <> b
  App_ f x   -> f <> " " <> x
  Ann_ e t   -> e <> " : " <> t

--------------------------------------------------------------------------------
-- Logic Types (Simplified)
--------------------------------------------------------------------------------

-- | Logic term
data Logic a var
  = Free var
  | Ground (Reified a var)

-- | Reified representations (normally in LogicRepr class)
data family Reified a var

-- Nat
data instance Reified Nat var
  = ZR
  | SR (Logic Nat var)

-- Ty
data instance Reified Ty var
  = TUnitR
  | TArrR (Logic Ty var) (Logic Ty var)

-- Tm
data instance Reified Tm var
  = VarR (Logic Nat var)
  | UnitR
  | LamR (Logic Tm var)
  | AppR (Logic Tm var) (Logic Tm var)
  | AnnR (Logic Tm var) (Logic Ty var)

--------------------------------------------------------------------------------
-- Bridge: Convert Display Rules to ShowReified
--------------------------------------------------------------------------------

-- | Convert a Pat-based display function to work on Reified.
--
-- This is the magic that lets users write patterns on the original type
-- but have them work on Reified.
class FromDisplay a where
  -- | Convert Reified to Pat (extract constructor + children as D)
  toPat :: (forall t. FromDisplay t => Logic t var -> String)
        -> Reified a var
        -> Pat a

  -- | The user's display rules
  displayRules :: Pat a -> D

instance FromDisplay Nat where
  toPat sh ZR     = Pat "Z" []
  toPat sh (SR n) = Pat "S" [Lit (sh n)]

  displayRules = natDisplay

instance FromDisplay Ty where
  toPat sh TUnitR       = Pat "TUnit" []
  toPat sh (TArrR a b)  = Pat "TArr" [Lit (sh a), Lit (sh b)]

  displayRules = tyDisplay

instance FromDisplay Tm where
  toPat sh (VarR n)     = Pat "Var" [Lit (sh n)]
  toPat sh UnitR        = Pat "Unit" []
  toPat sh (LamR b)     = Pat "Lam" [Lit (sh b)]
  toPat sh (AppR f x)   = Pat "App" [Lit (sh f), Lit (sh x)]
  toPat sh (AnnR e t)   = Pat "Ann" [Lit (sh e), Lit (sh t)]

  displayRules = tmDisplay

--------------------------------------------------------------------------------
-- Test
--------------------------------------------------------------------------------

-- | Helper to display a ground term
displayGround :: (FromDisplay a, ProjectReified a) => a -> String
displayGround = showReifiedGround . projectReified

-- | Project a value to its Reified form
class FromDisplay a => ProjectReified a where
  projectReified :: a -> Reified a var

instance ProjectReified Nat where
  projectReified Z     = ZR
  projectReified (S n) = SR (Ground (projectReified n))

instance ProjectReified Ty where
  projectReified TUnit       = TUnitR
  projectReified (TArr a b)  = TArrR (Ground (projectReified a)) (Ground (projectReified b))

instance ProjectReified Tm where
  projectReified (Var n)   = VarR (Ground (projectReified n))
  projectReified Unit      = UnitR
  projectReified (Lam b)   = LamR (Ground (projectReified b))
  projectReified (App f x) = AppR (Ground (projectReified f)) (Ground (projectReified x))
  projectReified (Ann e t) = AnnR (Ground (projectReified e)) (Ground (projectReified t))

-- | Show a fully ground Reified value
showReifiedGround :: FromDisplay a => Reified a var -> String
showReifiedGround reified =
  let pat = toPat showLogicGround reified
      d   = displayRules pat
  in renderD (error "Child should be Lit by now") d

showLogicGround :: FromDisplay a => Logic a var -> String
showLogicGround (Free _)   = "?"
showLogicGround (Ground r) = showReifiedGround r

-- Examples:
-- >>> displayGround (S (S Z))
-- "S S 0"
--
-- >>> displayGround (TArr TUnit TUnit)
-- "Unit → Unit"
--
-- >>> displayGround (App (Lam (Var Z)) Unit)
-- "λ. var 0 ()"
